cm_video_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles import views
from django.urls import re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("video.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', views.serve),]

video/urls.py
from django.urls import path
from video import views

app_name = 'video'

urlpatterns = [
    path('', views.top_page, name='top_page'),
    path('video/index/', views.IndexView.as_view(), name='index'),
    path('video/<int:pk>/', views.VideoDetailView.as_view(), name='video_detail'),
    path('video/new/', views.CreatePostView.as_view(), name='post_new'),
    path('video/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('video/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('video/login/', views.Login.as_view(), name='login'),
    path('video/logout/', views.Logout.as_view(), name='logout'),
    path('video/signup/', views.SignUp.as_view(), name='signup'),
    path('video/add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('video/category/<str:category>/', views.CategoryView, name='category'),
    path('search', views.search, name='search'),
]

video/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings
from django.utils import timezone


class Category(models.Model):
    name = models.CharField('カテゴリー', max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('add_category', kwargs={'pk': self.pk})


class Video(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False)
    caption = models.CharField('タイトル', max_length=200)
    category = models.ForeignKey(Category, verbose_name='カテゴリー', on_delete=models.PROTECT)
    video = models.FileField(upload_to='video/%y')
    thumb = models.FileField(upload_to='thumb/%', blank=True)
    content = models.TextField('内容')
    created = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.caption

video/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Video, Category
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class Video_post(forms.Form):
    category_data = Category.objects.all().values_list('name', 'name')
    category_choice = []
    for category in category_data:
        category_choice.append(category)

    # author = forms.ChoiceField(label='user', widget=forms.Select, choices=list(author_choice.items()))
    caption = forms.CharField(max_length=100, label='タイトル & タレント名..')
    category = forms.ChoiceField(label='カテゴリ', widget=forms.Select, choices=category_choice)
    video = forms.FileField(required=False)
    # thmub = forms.FileField()
    content = forms.CharField(label='content', widget=forms.Textarea(attrs={'placeholder': "クライアント名、タレント名、代理店、OA開始日、、、などなど"}))

    # class Meta:
    #     model = Video
    #     video = ('video', 'readonly')

    # class Meta:
    #     model = Video
    #     fields = ('author', 'caption', 'category', 'video', 'content')
    #

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

        # widgets ={
        #     'author': forms.Select(attrs={'class': 'form-control'}),
        #     'caption': forms.TextInput(attrs={'class': 'form_control'}),
        #     'category': forms.Select(choices=choice_list, attrs={'class': 'form_control'}),
        #     'video': forms.FileField(attrs={'class': 'form_control'}),
        #     'content': forms.TextInput(attrs={'class': 'form_control'})
        # }


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # username = forms.CharField()
    # password = forms.CharField(widget=forms.PasswordInput)


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

video/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect, resolve_url, get_object_or_404
from django.views.generic import View, CreateView, ListView
from .models import Video, Category
from .forms import Video_post, LoginForm, SignUpForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.db.models import Q
from functools import reduce
from operator import and_
from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_excption = True
    def test_func(self):
        post = Video.objects.get(id=self.kwargs['pk'])
        return post.author == self.request.user

def top_page(request):
    return render(request, 'video/top_page.html', {})


class IndexView(ListView):
    def get(self, request, *args, **kwargs):
        video = Video.objects.all().order_by('-id')
        paginator = Paginator(Video.objects.all().order_by('-id'), 5)
        video_page = request.GET.get('page')
        videos = paginator.get_page(video_page)

        return render(request, 'video/index.html', {
            'video': video,
            'videos': videos
        })


class VideoDetailView(View):
    def get(self, request, *args, **kwargs):
        post_video = Video.objects.get(id=self.kwargs['pk'],)
        return render(request, 'video/video_detail.html', {
            'post_video': post_video
        })


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Video

    def get(self, request, *args, **kwargs):
        form = Video_post(data=request.POST, files=request.FILES)
        success_url = reverse_lazy('/video/index')

        return render(request, 'video/video_post.html', {
            'form': form
        })

    def post(self, request, *args, **kwargs):
        form = Video_post(data=request.POST, files=request.FILES)

        # if request.method == "POST" and form.is_valid():
        if form.is_valid():
            post_data = Video()
            post_data.author = request.user
            post_data.caption = form.cleaned_data['caption']
            category = form.cleaned_data['category']
            category_data = Category.objects.get(name=category)
            post_data.category = category_data
            # if request.FILES:
            #     post_data.video = request.FILES.get('video')
            post_data.video = request.FILES['video']
            post_data.content = form.cleaned_data['content']
            post_data.save()
            return redirect('/video/index/')

        return render(request, 'video/video_post.html', {
            'form': form
        })



class PostEditView(OnlyMyPostMixin, CreateView):
    def get(self, request, *args, **kwargs):
        post_data = Video.objects.get(id=self.kwargs['pk'])
        form = Video_post(
            request.POST or None,
            initial={
                'author': post_data.author,
                'caption': post_data.caption,
                'category': post_data.category,
                'video': post_data.video,
                'content': post_data.content,
            })
        return render(request, 'video/video_post.html', {
            'form': form
        })

    def post(self, request, *args, **kwargs):
        form = Video_post(data=request.POST, files=request.FILES)

        if form.is_valid():
            post_data = Video.objects.get(id=self.kwargs['pk'])
            post_data.caption = form.cleaned_data['caption']
            if request.FILES:
                post_data.video = request.FILES.get('video')
            category = form.cleaned_data['category']
            category_data = Category.objects.get(name=category)
            post_data.category = category_data
            post_data.content = form.cleaned_data['content']
            post_data.save()
            return redirect('/video/index/', self.kwargs['pk'])

        return render(request, 'video/video_post.html', {
            'form': form
        })


class PostDeleteView(OnlyMyPostMixin, View):
    def get(self, request, *args, **kwargs):
        post_data = Video.objects.get(id=self.kwargs['pk'])
        return render(request, 'video/post_delete.html', {
            'post_data': post_data
        })

    def post(self, request, *args, **kwargs):
        post_data = Video.objects.get(id=self.kwargs['pk'])
        post_data.delete()
        return redirect('/video/index/')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'video/login.html'

    def get_success_url(self):
        messages.success(self.request, 'ログインしました')
        return resolve_url('video:index')


class Logout(LogoutView):
    template_name = 'video/logout.html'

    def get_success_url(self):
        messages.warning(self.request, 'ログアウトしました')
        return resolve_url('video:top_page')



class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'video/signup.html'
    success_url = reverse_lazy('video:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.info(self.request, 'ユーザー登録しました')
        return HttpResponseRedirect(self.get_success_url())


def search(request):
    if request.method == 'POST':
        keyword = request.POST['keyword']
        videos = Video.objects.order_by('-id').filter(content__contains=keyword)
        return render(request, 'video/index.html', {
            'keyword': keyword,
            'videos': videos
        })
    else:
        return render(request, 'video/index.html', {})


class AddCategoryView(CreateView):
    model = Category
    template_name = 'video/category_list.html'
    fields = '__all__'

    def get_success_url(self):
        messages.warning(self.request, 'カテゴリ追加しました')
        return resolve_url('video:index')

#
# def CategoryView(request, category):
#     if request.method == 'GET':
#         # category = get_object_or_404(Category, name=category)
#         category = Category.objects.get(name=category)
#         # category_post = Video.objects.all().order_by('-id').filter(name=category)
#         category_post = Video.objects.all().filter(category=category)
#         return render(request, 'video/categories.html', {
#             'category': category,
#             'category_post': category_post
#         })
#     else:
#         return render(request, 'video/index.html', {})


def CategoryView(request, category):
    if request.method == 'GET':
        # category = get_object_or_404(Category, name=category)
        category = Category.objects.get(name=category)
        category_post = Video.objects.all().order_by('-id').filter(category=category)
        return render(request, 'video/categories.html', {
            'category': category,
            'category_post': category_post
        })

    else:
        return render(request, 'video/index.html', {})



# class CategoryView(View):
#     def get(self, request, *args, **kwargs):
#         category_data = Category.objects.get(name=self.kwargs['category'])
#         post_data = Video.objects.order_by('-id').filter(category=category_data)
#         return render(request, 'video/index.html', {
#             'post_data': post_data
#         })

video/templates/video/base.html
{% load static %}
<!doctype html>
<html lang="ja" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'video/style.css' %}">

    <title>COMMERCIAL</title>
</head>

<body class="d-flex flex-column h-100">

<header class="p-5 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap justify-content-center" >
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white">
                <svg class="bi me-2" width="40" height="32" role="img">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% if user.is_authenticated %}
                <li><a href="{% url 'video:index' %}" class="nav-link text-white" id="header-text-size">Home</a></li>
                {% else %}
                <li><a href="{% url 'video:login' %}" class="nav-link text-white" id="header-text-size">Home</a></li>
                {% endif %}
<!--                                <li><a href="#" class="nav-link px-2 text-white">Features</a></li>-->
                <li><a href="https://www.stardust.co.jp/" class="nav-link text-white" id="header-text-size">About</a></li>

                {% if user.is_authenticated %}
                <li><a href="{% url 'video:add_category' %}" class="nav-link text-white" id="header-text-size">カテゴリ追加</a></li>
                {% endif %}
            </ul>

            {% if user.is_authenticated %}
            <div class="text-end">
                <a class="green" href="{% url 'video:post_new' %}">
<!--                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-film text-white" viewBox="0 0 16 16">-->
<!--                    <path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z"/>-->
<!--                    </svg>-->
                    <button type="button" class="btn btn-outline-light me-2" id="newpost-bt">NewPost</button>
                </a>
                <a class="" href="{% url 'video:logout' %}">
                    <button type="button" class="btn btn-warning logout-bt me-2">Logout</button>
                </a>
                <a href="{% url 'video:signup' %}">
                    <button type="button" class="btn btn-warning signup-bt me-2">Signup</button>
                </a>
            </div>
            {% else %}
            <div class="text-end">
                <a href="{% url 'video:login' %}">
                    <button type="button" class="btn btn-outline-light login-bt">Login</button>
                </a>
            </div>
            {% endif %}
            {% if user.is_authenticated %}
            <div>
                <form method=POST action="{% url 'video:search' %}" class="d-flex input-group">
                    {% csrf_token %}
                    <input type="text" class="form-control w-80 me-2 rounded-pill" name="keyword" placeholder="Search...">
                    <button class="btn btn-outline-success serch" type="submit">検索</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</header>

<!-- Begin page content -->
<main>
    <div class="back-ground">
        {% if messages %}
        <br>
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock %}
    </div>
</main>

<footer class="footer mt-auto bg-dark">
    <div class="container">
        <span class="text-muted">footer</span>
    </div>
</footer>


<!--<script src="/docs/5.1/dist/js/bootstrap.bundle.min.js"-->
<!--        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"-->
<!--        crossorigin="anonymous"></script>-->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

</body>
</html>

video/templates/video/categories.html
{% extends "video/base.html" %}

{% block content %}
<br>
<div class="container">
    <h1>{{ category }}</h1>

    {% for post in category_post %}

    <h2 class="text-center">{{ post.caption }}<small><span class="small">-<a
            href="{% url 'video:category' post.category %}">{{ post.category }}</a></span></small></h2>

    <video class="video" controls="controls" width="100%">
        {% if post.video %}
        <source src="{{ post.video.url }}" type="video/mp4">
        {% endif %}
    </video>
    <h5 class="mt-2 mb-5">{{ post.content | safe | linebreaksbr | urlize }}</h5>
    <div class="">{{ post.created | date }} by {{ post.author }}</div>
    <a href="{% url 'video:video_detail' post.id %}">
        <button class="btn btn-secondary btn-lg">詳細</button>
    </a>
    <hr>
    {% endfor %}

    <br>
</div>
{% endblock %}

video/templates/video/category_list.html
{% extends "video/base.html" %}

{% block content %}

{% if user.is_authenticated %}

<div class="container">
    <br>
    <h1 class="addcategory-toptitle">カテゴリー追加</h1>
    <br>
    <br>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}

            {{ form.as_p }}
            <br>
            <button class="btn btn-secondary" id="addcategory-btn">カテゴリ追加</button>
        </form>
    </div>
    {% else %}
    YOU'RE NOT ALLOWED HERE!!(and you know it ...)
</div>
{% endif %}


{% endblock %}

video/templates/video/index.html
{% extends 'video/base.html' %}

{% block content %}
<div class="container">
    <div class="">
        <h1 class="display-1" id="toptitle">Commercial Share Space</h1>
        <h5>表示は投稿順。<br>
            企業名、商品名、クライアント名、代理店、制作会社、監督、AD、HM、STYなど含め詳細へ記載<br>
        </h5>
        <hr>
    </div>

    <div class="d-flex">
        <div class="col-md-9">
            {% csrf_token %}
            <br>
            {% for x in videos %}
            <h2 class="text-center" id="video-titele-text">{{ x.caption }}<small><span class="small" id="video-titele-text">-<a href="{% url 'video:category' x.category %}">{{ x.category }}</a></span></small></h2>

            <video class="video" controls="controls" width="100%">
                {% if x.video %}
                <source src="{{ x.video.url }}" type="video/mp4">
                {% endif %}
            </video>
            <h5 class="mt-2 mb-5">{{ x.content | truncatechars_html:50 | safe | linebreaksbr | urlize }}</h5>
            <div class="">{{ x.created | date }} by {{ x.author }}</div>
            <a href="{% url 'video:video_detail' x.id %}">
                <button class="btn btn-secondary btn-lg">詳細</button>
            </a>
            <hr>
            <br>
            {% endfor %}
        </div>

        <div class="col-md-3 mx-3">
            <div class="card">
                <h5 class="card-header" id="index-category-list-title">カテゴリー</h5>
                <div class="card-body">
                    <div class="row">
                        {% for category in category_data %}
                        <div class="col-md-6">
                            <ul class="list-unstyled">
                                {% csrf_token %}
                                <li>
                                    <a href="{% url 'video:category' category %}" method="GET" id="index-category-list-name">{{ category.name }}</a>
                                </li>
                            </ul>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if videos.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ videos.previous_page_number }}">previous</a>
            {% endif %}
             Page {{ videos.number }} of {{ videos.paginator.num_pages }}.
            {% if videos.has_next %}
                <a href="?page={{ videos.next_page_number }}">next</a>
                <a href="?page={{ videos.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

<br>
{% endblock %}

video/templates/video/login.html
{% extends "video/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <br>
            <h2>Login</h2>
            <form action="." method="post">
                {% csrf_token %}
                {{ forms.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                {% endfor %}
                <br>
                <button type="submit" class="btn-primary btn-lg">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

video/templates/video/logout.html
{% extends "video/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <br>
            <h2>Logout</h2>
            <form action="." method="post">
                {% csrf_token %}
                <br>
                <p>ログアウトしました</p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

video/templates/video/pagination.html
{% extends "video/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <br>
            <h2>Signup</h2>
            <form action="." method="post">
                {% csrf_token %}
                {{ forms.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                {% endfor %}
                <br>
                <button type="submit" class="btn-primary btn-lg">Signup</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

(base) kamataryouhei@RK video % cat pagination.html     
{% extends 'video/base.html' %}


{% block content %}

{% endblock %}

video/templates/video/post_delete.html
{% extends 'video/base.html' %}

{% block content %}

<div class="container">
    <h2 class="my-4">{{ post_data.caption }}</h2>
    <hr>

    <h5 class="my-4">削除します</h5>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger">Delete</button>
    </form>
</div>
{% endblock %}

video/templates/video/search.html
{% extends "video/base.html" %}

{% block content %}


<br>

{% if searched %}
<!--    <h1>You Searched For...{{ searched }} </h1>-->
    <br>
    <br>
        {% for video in videos %}
        <a href="{% url 'video:video_detail' video.id %}">{{ video }}</a><br>
        {% endfor %}
{% else %}

<h1> Hey! you forget to Search For ...</h1>

{% endif %}

{% endblock %}

video/templates/video/signup.html
{% extends "video/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <br>
            <h2>Signup</h2>
            <form action="." method="post">
                {% csrf_token %}
                {{ forms.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                {% endfor %}
                <br>
                <button type="submit" class="btn-primary btn-lg">Signup</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

video/templates/video/top_page.html
{% extends 'video/base.html' %}

{% block content %}
<div class="">
    <div class="bg-dark bg-gradient vw-100 vh-100 d-flex flex-column align-items-center justify-content-center">
        <div class="">
            <h1 class="text-light" id="toptitle">Commercial Share Space</h1>
        </div>
        <br>
        <div class="">
            <h3 class="text-light text-center">
                CM動画の共有スペースとして作成しました<br>
                OAしてるのに "見たことない" という事を避けられたらという思いです。<br>
                基本的には完成物 & 既にOAしているCM掲載を想定してます<br>
                みなさんの意見も聞きながら改良を加えて行けたら良いのではないかと思っております<br>
            </h3>
        </div>
        <br>
<!--        <div class="">-->
<!--            <p><a href="{% url 'video:login' %}" class="btn btn-outline-light">さらに詳しく</a></p>-->
<!--        </div>-->
    </div>
</div>
{% endblock %}

video/templates/video/video_detail.html
{% extends 'video/base.html' %}

{% block content %}
<div class="container">
    <h2 class="my-4">{{ post_video.caption }} </h2>
    <p>{{ post_video.category }}</p>
    <video class="embed-responsive embed-responsive-16by9 mb-3" controls="controls" width="100%">
        {% if post_video.video %}
        <source src="{{ post_video.video.url }}" type="video/mp4">
        {% endif %}
    </video>

    {% if user.is_authenticated %}
    <div class="d-flex mb-5">
        <a href="{% url 'video:post_edit' post_video.id %}" class="btn m-1" id="detail-edit-btn">編集</a>
        <a href="{% url 'video:post_delete' post_video.id %}" class="btn btn-danger m-1" id="delete-btn">削除</a>
        <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-dark m-1" id="back-btn">戻る</a>
    </div>
    {% endif %}

<p>{{ post_video.content | safe | linebreaksbr | urlize }}</p>

<p class="mb-3">{{ post_video.created }} by {{ post_video.author }}</p>

</div>
{% endblock %}% 

video/templates/video/video_post.html
{% extends 'video/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="my-4">
        <h2>NEW POST</h2>
    </div>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>Title</label >
            {{ form.caption }}
        </div>
        <br>

        <div class="form-group">
            <label>Category</label>
            {{ form.category }}
        </div>
        <br>

        <div class="form-group">
            <label>Video</label>
            {{ form.video }}
        </div>
        <br>

        <div class="form-group">
            <label>content</label>
            {{ form.content }}
        </div>
        <br>

        <button class="btn btn-dark" type="submit">POST</button>
    </form>
</div>
{% endblock %}